{
 "title": "Garage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "poort knop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"garage_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"garage_knop\")"
    }
   ]
  },
  {
   "title": "poort beweging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"garage_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"garage_voortgang\")"
    }
   ]
  },
  {
   "title": "poort status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"garage_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"garage_status\")"
    }
   ]
  },
  {
   "title": "vochtigheid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"garage_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"garage_vochtigheid\")"
    }
   ]
  },
  {
   "title": "temperatuur",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"garage_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"garage_temperatuur\")"
    }
   ]
  },
  {
   "type": "welcome",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gettingstarted",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest from the blog",
   "type": "news",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {}
   ]
  }
 ]
}